package com.kp.appdirect.management;

public interface ErrorCodeConstantParams {

	//ERROR CODE CONSTANT FOR APP UPLOAD
	static final int APP_UPLOAD_R4G_SUCC_DB_SUCC_TABULAR_SUCC_APPMAP_SUCC_CACHE_SUCC 				= 0;
	static final int APP_UPLOAD_R4G_SUCC_DB_SUCC_TABULAR_SUCC_APPMAP_SUCC_CACHE_UNSUCC 				= -31;
	static final int APP_UPLOAD_R4G_SUCC_DB_SUCC_TABULAR_SUCC_APPMAP_UNSUCC_CACHE_UNSUCC 			= -32;
	static final int APP_UPLOAD_R4G_SUCC_DB_SUCC_TABULAR_UNSUCC_APPMAP_UNSUCC_CACHE_UNSUCC 			= -33;
	static final int APP_UPLOAD_R4G_UNSUCC_REMOTE_FILE_DOESNOT_EXIST 								= -34;
	static final int APP_UPLOAD_R4G_UNSUCC_DOWNLOAD_FILE_CORRUPTED 									= -35;
	static final int APP_UPLOAD_R4G_UNSUCC_ERROR_IN_UPLOAD_FILE_FROM_REMOTE_LOCATION 				= -36;
	static final int APP_UPLOAD_DATABASE_CHECK_ERROR 												= -37;
	static final int APP_UPLOAD_DATABASE_WRITE_ERROR 												= -38;
	
	//ERROR CODE CONSTANT FOR APP DELETE
	static final int APP_DELETE_DB_NOT_EXIST_APP_PARAMETER_SUCC_MAP_STREAM_SUCC 					= -50;
	static final int APP_DELETE_DB_SUCC_APP_PARAMETER_SUCC_MAP_STREAM_SUCC 							= -51;
	static final int APP_DELETE_DB_NOT_EXIST_APP_PARAMETER_SUCC_MAP_STREAM_UNSUCC 					= -52;
	static final int APP_DELETE_DB_SUCC_APP_PARAMETER_SUCC_MAP_STREAM_UNSUCC 						= -53;
	static final int APP_DELETE_DB_NOT_EXIST_APP_PARAMETER_SUCC_MAP_STREAM_NOT_EXIST 				= -54;
	static final int APP_DELETE_DB_SUCC_APP_PARAMETER_SUCC_MAP_STREAM_NOT_EXIST 					= -55;
	static final int APP_DELETE_DB_NOT_EXIST_APP_PARAMETER_MAP_NOT_EXIST 							= -56;
	static final int APP_DELETE_DB_SUCC_APP_PARAMETER_MAP_NOT_EXIST 								= -57;
	static final int APP_DELETE_ERROR_IN_DELETING_APP_FROM_R4G_APP_SERVER 							= -58;
	
}
